### PR TITLE
Added 2 new rules in 'rlx'

### PR DESCRIPTION
**Pull request by anniedhempe**
Example:

Old output:
```
echo "मैं आम खा रहा हूं" | apertium -d . -f none hin-tagger
^मैं<prn><pers><p1><sg><nom>$ 
^आम<adj><mfn><sp>$ 
^खा<vblex><tv><stem>$ 
^रह<vaux><perf><m><sg>$ 
^हो<vbser><pres><p1><mf><sg>$
```

New output:
```
echo "मैं आम खा रहा हूं" | apertium -d . -f none hin-tagger
^मैं<prn><pers><p1><sg><nom>$ 
^आम<n><m><sg><nom>$ 
^खा<vblex><tv><stem>$ 
^रह<vaux><perf><m><sg>$ 
^हो<vbser><pres><p1><mf><sg>$
```

### CODE REVIEW

**Comment by khannatanmai** [comment]
I'm not able to check what you added in the rlx file cause it's not showing the changes to me, just says the entire file was deleted and a new one added.

**Comment by TinoDidriksen** [comment]
Most likely caused by it changing from \n newlines to Windows \r\n, which is in turn most likely caused by using Github's interface for uploading files because that bypasses .gitattributes. Use a real git client - never use Github's website for managing files.

**Comment by khannatanmai** [comment]
@anniedhempe Since you work with Apertium in a VM anyway, it might be a good idea to edit the files in Linux as well, and use git from the command line to upload files.

**Comment by khannatanmai** [comment]
```
SELECT N IF
  (-1 Prn)
  (0 Adj)
  (0 N)
  (1 Vblex);
```
shouldn't have the pronoun, it's not really a general rule, plus just checking if it's followed by a verb is enough to say that it's a noun and not an adjective

**Comment by khannatanmai** [comment]
```
SELECT SingularNoun IF
	(-1 SingularPronoun)
	(0 SingularNoun)
	(0 PluralNoun);
```
This says that if a noun follows a singular pronoun then it will be singular. Why though? A plural noun can follow a singular pronoun as well?

**Pull request closed without merging**
